[test]

# always enable coverage
coverage = true

# to set different thresholds for lines and functions
coverageThreshold = { lines = 0.8, functions = 0.8 }

coverageReporter  = ["text", "lcov"]  # default ["text"]
coverageDir = "coverage"  # default "coverage"